[[libcint]]
arch = "aarch64"
git-tree-sha1 = "864d913f442be26b0deb48862eda383756038279"
os = "macos"

    [[libcint.download]]
    sha256 = "6b1e2f53b1aa6dadc899fa9c21561676d03202dc72616328d5164bede2867266"
    url = "https://github.com/JuliaBinaryWrappers/libcint_jll.jl/releases/download/libcint-v6.1.2+0/libcint.v6.1.2.aarch64-apple-darwin.tar.gz"
[[libcint]]
arch = "aarch64"
git-tree-sha1 = "d29cc715da1e752d868a95906d3b6ef932af3cf9"
libc = "glibc"
os = "linux"

    [[libcint.download]]
    sha256 = "b4b422eb10a474bf760b2315f203edbc10b6c0e0b2eb3003ec39485fafe5f462"
    url = "https://github.com/JuliaBinaryWrappers/libcint_jll.jl/releases/download/libcint-v6.1.2+0/libcint.v6.1.2.aarch64-linux-gnu.tar.gz"
[[libcint]]
arch = "x86_64"
git-tree-sha1 = "8fafefe497dc3c7d1abd81b827a4b6cdb87ba445"
os = "macos"

    [[libcint.download]]
    sha256 = "f7f1e0e81a658f0d8086afb37d2d76a0e59fc52ff1d4fd1a891d751aea72cdc7"
    url = "https://github.com/JuliaBinaryWrappers/libcint_jll.jl/releases/download/libcint-v6.1.2+0/libcint.v6.1.2.x86_64-apple-darwin.tar.gz"
[[libcint]]
arch = "x86_64"
git-tree-sha1 = "e5179b19efff70736be1762dac446076324b7393"
libc = "glibc"
os = "linux"

    [[libcint.download]]
    sha256 = "2a180e78664dc6c8ea84cacb0376e2213a8e3280d1203a6bf6dc81e21dfd060a"
    url = "https://github.com/JuliaBinaryWrappers/libcint_jll.jl/releases/download/libcint-v6.1.2+0/libcint.v6.1.2.x86_64-linux-gnu.tar.gz"
