[[libcint]]
arch = "x86_64"
git-tree-sha1 = "0bf8c56b3cec50467ec45dfef734b8c3b71a064a"
os = "macos"

    [[libcint.download]]
    sha256 = "6db5f4287f76284e2a552e2ff6e228cd1c20fa755a9e4363618f6f59ef81081d"
    url = "https://github.com/JuliaBinaryWrappers/libcint_jll.jl/releases/download/libcint-v4.4.6+1/libcint.v4.4.6.x86_64-apple-darwin.tar.gz"
[[libcint]]
arch = "x86_64"
git-tree-sha1 = "a6aa5d8dd27264f13a91e8c1a77ccb974c6afeca"
libc = "glibc"
os = "linux"

    [[libcint.download]]
    sha256 = "0c14fbba13649feb59d5c6d54ff5b859f2516e205f83f557285f0a9955cf5dee"
    url = "https://github.com/JuliaBinaryWrappers/libcint_jll.jl/releases/download/libcint-v4.4.6+1/libcint.v4.4.6.x86_64-linux-gnu.tar.gz"
