# Autogenerated wrapper script for libcint_jll for aarch64-apple-darwin
export libcint

JLLWrappers.@generate_wrapper_header("libcint")
JLLWrappers.@declare_library_product(libcint, "@rpath/libcint.5.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libcint,
        "lib/libcint.5.1.7.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
